### ISSUE TITLE
VPN profiles being created with old IPs

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DNP_DAPPMANAGER#457] opened 2020-11-30 08:52 UTC
<img width="878" alt="Screenshot 2020-11-30 at 09 51 59" src="https://user-images.githubusercontent.com/19168735/100588083-b29be380-32f1-11eb-8e9e-91e790184a13.png">

<img width="787" alt="Screenshot 2020-11-30 at 09 50 43" src="https://user-images.githubusercontent.com/19168735/100587949-84b69f00-32f1-11eb-8325-57f44d5bd184.png">

**Comment by pablomendezroyo** [comment] 2020-12-02 11:20
Also, would be nice to have the local IP in the dappnode identity section (top right in the UI). Users would have access to their public IP together with the local IP.

![Screenshot from 2020-12-02 12-11-21](https://user-images.githubusercontent.com/41727368/100866324-c7ff4200-3498-11eb-9c0b-0c2cf376e655.png)

**Comment by dapplion** [comment] 2020-12-02 18:58
> Also, would be nice to have the local IP in the dappnode identity section (top right in the UI). Users would have access to their public IP together with the local IP.
> 
> ![Screenshot from 2020-12-02 12-11-21](https://user-images.githubusercontent.com/41727368/100866324-c7ff4200-3498-11eb-9c0b-0c2cf376e655.png)

Agree! That's a great suggestion

**Comment by dapplion** [comment] 2020-12-09 10:39
Duplicate of https://github.com/dappnode/DNP_DAPPMANAGER/issues/463

**Closed by dapplion** 2020-12-09 10:39 UTC
Labels: P0, bug
