### ISSUE TITLE
Dappnode should warn the user when it's not connected to the internet

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DNP_DAPPMANAGER#1845] opened 2024-02-15 12:33 UTC
I just had a debugging session with a user and it turns out the problem was that the dappnode wasn't able to access internet.
The same could happen if the user turns it on without being plugged to the router via ethernet.
We can save lots of hours of debugging by making the dappnode detect internet access and offering ways to solve it to the users.

**Comment by Pol-Lanski** [comment] 2024-02-22 09:03
@mateumiralles after creating the logic of detecting when there is internet and when there it isn't we should talk about *how* we offer alternatives to the user. 
Some ideas here for safekeeping:
- Guide them to the documentation (it is possible that they don't have working internet)
- Show a guide within dappmanager to plug ethernet, check ethernet cable, change ethernet port from router and other common ways the dappnode could be NOT connected to ethernet.

**Comment by pablomendezroyo** [comment] 2024-02-22 10:43
Duplicate of https://github.com/dappnode/DNP_DAPPMANAGER/issues/467

**Comment by pablomendezroyo** [comment] 2024-03-04 16:26
Implemented thanks to @mateumiralles  ! 🚀

**Closed by pablomendezroyo** 2024-03-04 16:26 UTC
