### ISSUE TITLE
Measure network consumption

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_DAPPMANAGER#238] opened 2019-07-09 16:28 UTC
Hi!!! some users have expressed that they would like to see in the admin UI the network consumption of the DAppNode. If it is very  complicated to make by package , at least it would be nice to have the complete network consumption during the last 30 days

**Comment by dapplion** [comment] 2019-08-12 11:25
Duplicate of https://github.com/dappnode/DAppNode/issues/108

**Closed by dapplion** 2019-08-12 11:25 UTC
Labels: enhancement
