### ISSUE TITLE
Beacon chain and validator can not be restarted separately

### ISSUE THREAD

**Issue by sembrestels** [dappnode/DNP_DAPPMANAGER#460] opened 2020-11-29 21:56 UTC
It is not possible to restart individual containers from the info tab interface. When done, these are the errors:

![Screenshot from 2020-11-29 22-51-37](https://user-images.githubusercontent.com/931684/100554603-fd880d80-3295-11eb-9c47-80fc38095152.png)
![Screenshot from 2020-11-29 22-52-55](https://user-images.githubusercontent.com/931684/100554606-01b42b00-3296-11eb-85ce-89b3ff0cbd31.png)

**Comment by dapplion** [comment] 2020-11-30 14:44
Duplicate of https://github.com/dappnode/DNP_DAPPMANAGER/issues/454 will release a fix soon

**Closed by dapplion** 2020-11-30 14:44 UTC
