### ISSUE TITLE
Dark Mode | Unreadable Wireguard credentials

### ISSUE THREAD

**Issue by DAppDanil** [dappnode/DNP_DAPPMANAGER#1490] opened 2023-06-09 16:51 UTC
VPN -> Wireguard -> Get link
It's how credentials are seen on darkmode, unreadable
Needs a re-coloring:
- background gray/black
- letters white 
![image](https://github.com/dappnode/DNP_DAPPMANAGER/assets/109515640/bda9bfe6-9888-4b3a-a4ff-3e113d39b122)

**Comment by pablomendezroyo** [comment] 2023-09-25 09:07
Duplicate of https://github.com/dappnode/DNP_DAPPMANAGER/issues/1573

**Closed by pablomendezroyo** 2023-09-25 09:07 UTC
Labels: UIX
